apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ingress.yml

patchesStrategicMerge:
  - gateway-deployment-patch.yml

images:
  - name: ghcr.io/your-org/distributed-rate-limiter-gateway
    newName: ghcr.io/your-org/distributed-rate-limiter-gateway
    newTag: "1.0.0"
