apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
  labels:
    app: distributed-rate-limiter-gateway
data:
  SPRING_PROFILES_ACTIVE: prod
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  REDIS_POOL_MAX_ACTIVE: "64"
  REDIS_POOL_MAX_IDLE: "32"
  REDIS_POOL_MIN_IDLE: "8"
  UPSTREAM_CONNECT_TIMEOUT_MS: "2000"
  UPSTREAM_READ_TIMEOUT_MS: "5000"
  SERVICE_A_URL: http://distributed-rate-limiter-gateway/backend/service-a
  SERVICE_B_URL: http://distributed-rate-limiter-gateway/backend/service-b
