apiVersion: v1
kind: Secret
metadata:
  name: gateway-secrets
  labels:
    app: distributed-rate-limiter-gateway
type: Opaque
stringData:
  JWT_SECRET_BASE64: "replace-with-your-base64-secret"
  ACTUATOR_API_KEY: "replace-with-strong-actuator-key"
  INTERNAL_ROUTING_TOKEN: "replace-with-strong-internal-routing-token"
