apiVersion: v1
kind: Service
metadata:
  name: distributed-rate-limiter-gateway
  labels:
    app: distributed-rate-limiter-gateway
spec:
  selector:
    app: distributed-rate-limiter-gateway
  ports:
    - name: http
      port: 80
      targetPort: http
  type: ClusterIP
